runtime: nodejs20
service: exchange-book
instance_class: F1

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(js|css|map|json|png|jpg|jpeg|gif|ico|svg|webp))
    static_files: build/\1
    upload: build/.*\.(js|css|map|json|png|jpg|jpeg|gif|ico|svg|webp)

  - url: /.*
    static_files: build/index.html
    upload: build/index.html